apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mon-app-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mon-app-secret # Nom du secret k8s qui sera créé
    creationPolicy: Owner
  dataFrom:
  # La clé Vault sera redéfinie dans l'overlay (ex: secret/data/staging/mon-app)
  - extract:
      key: "secret/data/mon-app"
