apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mon-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alex-dembele/aws-gitops-infrastructure.git'
    targetRevision: HEAD
    path: gitops/apps/mon-app/overlays/staging
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
