apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tools-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/alex-dembele/aws-gitops-infrastructure.git'
    targetRevision: HEAD
    path: gitops/tools
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
